### ISSUE TITLE
#bug 运行该程序时遇到问题

### ISSUE THREAD

**Issue by Higanoneko** [PufferBlue/HelloCamera#1]
我在Windows 11 22H2 (22623.1180) 上运行该程序遇到问题
python版本为3.9.14
requirement.txt内的依赖项已安装
下面是输出的错误提示：

```
Exception ignored in: <bound method VideoCapture._frame_arrived_handler of <videocapture.VideoCapture object at 0x00000139BE710BB0>>
Traceback (most recent call last):
  File "D:\Projects\HelloCamera\HelloCamera-main\videocapture.py", line 215, in _frame_arrived_handler
    self.current_format["width"] * self.current_format["height"] * self._formatBits[self.current_format["type"]] / 8
KeyError: 'L8'
```

**Comment by Higanoneko** [comment]
刚刚去找了一下相关信息，或许是跟红外流有关？
https://learn.microsoft.com/zh-cn/windows-hardware/drivers/stream/infrared-stream-support-in-uvc

**Comment by CyberPuffer** [comment]
抱歉，好久没上Github了
这个应该是因为我只在代码里只写了NV12的帧大小，因为我的摄像头的图像格式是NV12

https://github.com/PufferBlue/HelloCamera/blob/9c30e32b5ba9021957bee1ea36876acc7f320fc0/videocapture.py#L50

而看起来你的摄像头的图像格式是L8，所以需要加上L8的帧大小，但是pyvirtualcam似乎并不支持L8格式，所以你后续可能还需要自己做格式转换，把L8转换到pyvirtualcam支持的图像格式才能输出

https://letmaik.github.io/pyvirtualcam/#pyvirtualcam.PixelFormat

**Comment by Higanoneko** [comment]
> 抱歉，好久没上Github了 这个应该是因为我只在代码里只写了NV12的帧大小，因为我的摄像头的图像格式是NV12
> 
> https://github.com/PufferBlue/HelloCamera/blob/9c30e32b5ba9021957bee1ea36876acc7f320fc0/videocapture.py#L50
> 
> 而看起来你的摄像头的图像格式是L8，所以需要加上L8的帧大小，但是pyvirtualcam似乎并不支持L8格式，所以你后续可能还需要自己做格式转换，把L8转换到pyvirtualcam支持的图像格式才能输出
> 
> https://letmaik.github.io/pyvirtualcam/#pyvirtualcam.PixelFormat

那么您有推荐的NV12格式的 Windows Hello IR Cam 推荐吗？
